swagger: "2.0"
info:
  description: "Created by Terraform"
  version: "1.0.0"
  title: "${title}"
basePath: "/default"
schemes:
  - "https"
paths:
  /names:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${aws_region_name}:lambda:path/2015-03-31/functions/${get_lambda_function_arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
  /name:
    put:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      - name: "id"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "Test"
        required: true
        schema:
          $ref: "#/definitions/Test"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${aws_region_name}:lambda:path/2015-03-31/functions/${set_lambda_function_arn}/invocations
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  Test:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        minLength: 5
        maxLength: 5
        pattern: "^[0-9]*$"
      name:
        type: "string"
        minLength: 1
        maxLength: 20
        pattern: "^[a-zA-Z]*$"
    title: "Test"
x-amazon-apigateway-request-validators:
  本文、クエリ文字列パラメータ、およびヘッダーの検証:
    validateRequestParameters: true
    validateRequestBody: true